---
# tasks file for ansible-visual-basic
---
- name: Compose paths
  ansible.builtin.set_fact:
    sofia_path: "{{ sofia_share_root }}\\{{ sofia_subfolder }}"
    sofia_check_full: "{{ sofia_share_root }}\\{{ sofia_subfolder }}\\{{ file_check }}"
    sofia_in_full: "{{ sofia_share_root }}\\{{ sofia_subfolder }}\\{{ file_in }}"
    local_in_full: "{{ path_in }}\\{{ file_in }}"
    local_check_full: "{{ path_in }}\\{{ file_check }}"
    local_out_full: "{{ path_out }}\\{{ file_out }}"
    log_full: "{{ path_log }}\\{{ file_log }}"
    process_name: "ITF_IOFIN_ANTITERRORISMO"

- name: Init ret
  ansible.builtin.set_fact:
    ret: 0

- name: Get User
  ansible.builtin.command: >
    cmd whoami
  register: whoami
  changed_when: false
  failed_when: false

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] JOB {{ parent_build_id }} STARTED BY {{ (whoami.stdout | trim) }}" >> "{{ log_full }}"
  failed_when: false

- name: Get Hostname
  ansible.builtin.command: >
    cmd hostname
  register: hostname
  changed_when: false
  failed_when: false

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] ServerID: {{ hostname }} Time: {{ ansible_date_time.date }} {{ ansible_date_time.time }}" >> "{{ log_full }}"
  failed_when: false

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] Procedura {{ process_name }}" >> "{{ log_full }}"
  failed_when: false

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] .Inizio Folder Check" >> "{{ log_full }}"
  failed_when: false

- name: Check Sofia folder exists
  ansible.windows.win_stat:
    path: "{{ sofia_path }}"
  register: sofia_folder_stat
  failed_when: false

- name: Set ret for share/folder
  ansible.builtin.set_fact:
    ret: >-
      {% if sofia_folder_stat is failed %}
      30
      {% elif not sofia_folder_stat.stat.exists %}
      50
      {% else %}
      0
      {% endif %}

- name: Ensure local Input folder Exist
  ansible.windows.win_stat:
    path: "{{ path_in }}"
  register: folder_in_stat
  failed_when: false

- name: Set ret for folder Input
  ansible.builtin.set_fact:
    ret: "{{ 70 if (not folder_in_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Ensure local Output folder Exist
  ansible.windows.win_stat:
    path: "{{ path_out }}"
  register: folder_out_stat
  failed_when: false

- name: Set ret for folder Output
  ansible.builtin.set_fact:
    ret: "{{ 71 if (not folder_out_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Ensure local Log folder Exist
  ansible.windows.win_stat:
    path: "{{ path_log }}"
  register: folder_log_stat
  failed_when: false

- name: Set ret for folder Log
  ansible.builtin.set_fact:
    ret: "{{ 72 if (not folder_log_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Ensure local SAV folder Exist
  ansible.windows.win_stat:
    path: "{{ path_sav }}"
  register: folder_sav_stat
  failed_when: false

- name: Set ret for folder SAV
  ansible.builtin.set_fact:
    ret: "{{ 73 if (not folder_sav_stat.stat.exists) else 0 }}"
  when: ret == 0
    
- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] .Fine Folder Check con esito {{ ret }}" >> "{{ log_full }}"
  failed_when: false

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] ..Inizio File Check" >> "{{ log_full }}"
  failed_when: false

- name: Controllo File_Check exists
  ansible.windows.win_stat:
    path: "{{ sofia_check_full }}"
  register: sofia_check_stat
  failed_when: false
  when: ret == 0

- name: Set ret if check-file missing
  ansible.builtin.set_fact:
    ret: "{{ 10 if (not sofia_check_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Controllo File_CSV exists
  ansible.windows.win_stat:
    path: "{{ sofia_in_full }}"
  register: sofia_in_stat
  failed_when: false
  when: ret == 0

- name: Set ret if CSV-file missing
  ansible.builtin.set_fact:
    ret: "{{ 60 if (not sofia_in_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] ..Fine File Check con esito {{ ret }}" >> "{{ log_full }}"
  failed_when: false

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] ...Inizio Copia File" >> "{{ log_full }}"
  failed_when: false

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] ...Export {{ sofia_in_full }} to  {{ local_in_full }}" >> "{{ log_full }}"
  failed_when: false

- name: Calcolo hash del file sorgente
  ansible.builtin.command: >
    cmd /C certutil -hashfile "{{ sofia_in_full }}" {{ hash_algo }}
  register: hash_source_raw

- name: Estraggo hash sorgente
  set_fact:
    hash_source: "{{ hash_source_raw.stdout_lines[1] | trim }}"

- name: Copy input CSV from Sofia to local
  ansible.windows.win_copy:
    src: "{{ sofia_in_full }}"
    dest: "{{ local_in_full }}"
    remote_src: true
  register: copy_csv
  failed_when: false
  when: ret == 0

- name: Check copied file exists
  ansible.windows.win_stat:
    path: "{{ local_in_full }}"
  register: csv_stat
  failed_when: false
  when: ret == 0

- name: Set ret if output missing
  ansible.builtin.set_fact:
    ret: "{{ 0 if csv_stat.stat.exists else 61 }}"
  when: ret == 0

- name: Calcolo hash del file sorgente copiato
  ansible.builtin.command: >
    cmd /C certutil -hashfile "{{ local_check_full }}" {{ hash_algo }}
  register: hash_copied_source_raw

- name: Estraggo hash Sorgente copiato
  ansible.builtin.set_fact:
    hash_copied_source: "{{ hash_copied_raw.stdout_lines[1] | trim }}"

- name: Check hash
  set_fact:
    ret: "{{ 0 if hash_source == hash_copied_source else 62 }}"

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] ...Fine Copia File con esito {{ ret }}" >> "{{ log_full }}"
  failed_when: false

- name: Write log line
  ansible.builtin.shell: >
    cmd.exe /c "echo [{{ ansible_date_time.date }} {{ ansible_date_time.time }}] ....{{ (whoami.stdout | trim) }} {{ ansible_date_time.date }} {{ ansible_date_time.time }} Ret={{ ret }}" >> "{{ log_full }}"
  failed_when: false

- name: Fail if ret != 0
  ansible.builtin.fail:
    msg: "IOFIN Antiterrorismo failed with Ret={{ ret }}"
  when: ret != 0

{{ parent_build_id }}