---
# tasks file for ansible-visual-basic
---
- name: Compose paths
  ansible.builtin.set_fact:
    sofia_path: "{{ sofia_share_root }}\\{{ sofia_subfolder }}"
    sofia_check_full: "{{ sofia_share_root }}\\{{ sofia_subfolder }}\\{{ file_check }}"
    sofia_in_full: "{{ sofia_share_root }}\\{{ sofia_subfolder }}\\{{ file_in }}"
    local_in_full: "{{ path_in }}\\{{ file_in }}"
    local_out_full: "{{ path_out }}\\{{ file_out }}"
    local_sav_full: "{{ path_sav }}\\{{ file_out }}"
    log_full: "{{ path_log }}\\{{ file_log }}"
    etl_full: "{{ path_prog }}\\{{ etl_exe }}"

- name: Init ret
  ansible.builtin.set_fact:
    ret: 0

- name: Ensure local Input folder Exist
  ansible.windows.win_stat:
    path: "{{ path_in }}"
  register: folder_in_stat
  failed_when: false

- name: Set ret for folder Input
  ansible.builtin.set_fact:
    ret: "{{ 70 if (not folder_in_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Ensure local Output folder Exist
  ansible.windows.win_stat:
    path: "{{ path_out }}"
  register: folder_out_stat
  failed_when: false

- name: Set ret for folder Output
  ansible.builtin.set_fact:
    ret: "{{ 71 if (not folder_out_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Ensure local Log folder Exist
  ansible.windows.win_stat:
    path: "{{ path_log }}"
  register: folder_log_stat
  failed_when: false

- name: Set ret for folder Log
  ansible.builtin.set_fact:
    ret: "{{ 72 if (not folder_log_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Ensure local SAV folder Exist
  ansible.windows.win_stat:
    path: "{{ path_sav }}"
  register: folder_sav_stat
  failed_when: false

- name: Set ret for folder SAV
  ansible.builtin.set_fact:
    ret: "{{ 73 if (not folder_sav_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Check Input-file exists
  ansible.windows.win_stat:
    path: "{{ local_in_full }}"
  register: local_in_stat
  failed_when: false
  when: ret == 0

- name: Set ret if Input-file missing
  ansible.builtin.set_fact:
    ret: "{{ 63 if (not local_in_stat.stat.exists) else 0 }}"
  when: ret == 0

- name: Run ETL
  ansible.windows.win_command: '"{{ etl_full }}" {{ etl_arg }}'
  register: etl_run
  failed_when: false
  when: ret == 0

- name: Check output file exists
  ansible.windows.win_stat:
    path: "{{ local_out_full }}"
  register: out_stat
  failed_when: false
  when: ret == 0

- name: Set ret if output missing
  ansible.builtin.set_fact:
    ret: "{{ 0 if out_stat.stat.exists else 20 }}"
  when: ret == 0

- name: Copy output TXT from Output to SAV
  ansible.windows.win_copy:
    src: "{{ local_out_full }}"
    dest: "{{ local_sav_full }}"
    remote_src: true
  register: copy_txt
  failed_when: false
  when: ret == 0

- name: Check copied file exists
  ansible.windows.win_stat:
    path: "{{ local_sav_full }}"
  register: sav_stat
  failed_when: false
  when: ret == 0
  
- name: Set ret if sav missing
  ansible.builtin.set_fact:
    ret: "{{ 0 if sav_stat.stat.exists else 64 }}"
  when: ret == 0

- name: Get User
  ansible.builtin.command: >
    cmd whoami
  register: whoami
  changed_when: false
  failed_when: false

- name: Write log line
  ansible.windows.win_lineinfile:
    path: "{{ log_full }}"
    create: true
    line: "{{ (whoami.stdout | trim) }} {{ ansible_date_time.date }} {{ ansible_date_time.time }} Ret={{ ret }}"
  failed_when: false

- name: Delete check-file on Sofia
  ansible.windows.win_file:
    path: "{{ sofia_check_full }}"
    state: absent
  failed_when: false
  when: ret == 0

- name: Delete input CSV on Sofia
  ansible.windows.win_file:
    path: "{{ sofia_in_full }}"
    state: absent
  failed_when: false
  when: ret == 0

- name: Fail if ret != 0
  ansible.builtin.fail:
    msg: "IOFIN Antiterrorismo failed with Ret={{ ret }}"
  when: ret != 0



